//
@baseurl = http://127.0.0.1:8081
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjQyNjA1ODUsInVpZCI6MiwidXNlciI6IjI2MmZfOWI3NGQiLCJwaG9uZSI6IjE4NjgxNjM2NzQ5In0.EYg9AxR2-lvCVWJeSrqx0rGTjPMmIYJDmEsZKV7KiKk

// 健康检查
GET {{baseurl}}/healthz

###
// 服务探活 
GET {{baseurl}}/ready
###
// 测试接口
GET {{baseurl}}/test

###
// 手机号快速注册
POST {{baseurl}}/v1/user/regist

{
    "phone":"18681636749",
    "code": "123456"
}

###
// 手机号登录
POST {{baseurl}}/v1/user/k-login

{
    "phone":"18681636741",
    "code": "123456"
}

###
// 账号密码登录
POST {{baseurl}}/v1/user/login

{
    "user":"d5bf_9b746",
    "pass":"123456"
}

###
// 用户基本信息
GET {{baseurl}}/v1/user/info
Authorization: {{token}}

###
// 修改密码-手机号
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"phone",
    "phone":"18681636749",
    "code":"123456",
    "pass":"123123"
}

###
// 修改密码-旧密码
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"pass",
    "old_pass":"123123",
    "pass":"123456"
}

###
// 修改密码-邮箱
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"email",
    "email":"123@adm.com",
    "code":"123456",
    "pass":"123123"
}

###
// 更新基础信息
POST {{baseurl}}/v1/user/modinfo
Authorization: {{token}}

{
    "user": "kui",
    "nickname": "昊天",
    "truename": "王胜"
}

###
// 用户列表
GET {{baseurl}}/admin/user/list
Authorization: {{token}}
