//
@baseurl = http://127.0.0.1:8081
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NTU4OTA4NjgsInVpZCI6MywidXNlciI6Imd0YW5rXzVmNTc3NDliNzQ1IiwicGhvbmUiOiIxODY4MTYzNjc0MSJ9.ZjijZ3j-Fp80iZNmEPiAfR3qC7V8oM0SeZprV8LGfdk

###
// 健康检查
GET {{baseurl}}/healthz

###
// 服务探活 
GET {{baseurl}}/ready

###
// 手机号快速注册
POST {{baseurl}}/v1/user/regist

{
    "phone":"18681636742",
    "code": "123456"
}

###
// 手机号登录
POST {{baseurl}}/v1/user/k-login

{
    "phone":"18681636741",
    "code": "123456"
}

###
// 用户基本信息
GET {{baseurl}}/v1/user/info
Authorization: {{token}}

###
// 修改密码-手机号
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"phone",
    "phone":"18681636742",
    "code":"123456",
    "pass":"123123"
}

###
// 修改密码-旧密码
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"pass",
    "old_pass":"123123",
    "pass":"123456"
}

###
// 修改密码-邮箱
POST {{baseurl}}/v1/user/modpass
Authorization: {{token}}

{
    "type":"email",
    "email":"123@adm.com",
    "code":"123456",
    "pass":"123123"
}

###
// 账号密码登录
POST {{baseurl}}/v1/user/login

{
    "user":"d5bf_9b746",
    "pass":"123456"
}

###